apiVersion: v1
kind: Service
metadata:
  name: {{ include "lightpanda.fullname" . }}
  labels:
    {{- include "lightpanda.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ int .Values.service.port }}
      targetPort: cdp
      protocol: TCP
      name: cdp
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ int .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "lightpanda.selectorLabels" . | nindent 4 }}
